version: '2.1'
# Prometheus demonstration of the autopilot pattern

services:
  prometheus:
    build: ../../
    mem_limit: 1g
    restart: always
    dns:
      - 127.0.0.1
    ports:
      - 9090
    environment:
      - CONSUL=consul
      - CONSUL_AGENT=1
    links:
      - consul:consul


  # Start with a single host which will bootstrap the cluster.
  # In production we'll want to use an HA cluster.
  consul:
    image: pdouble16/autopilotpattern-consul:1.0.6-r2
    restart: always
    mem_limit: 128m
    environment:
      - CONSUL_DEV=1
    ports:
      - 8500
    dns:
      - 127.0.0.1
