---
version: "2.1"

services:
  consul:
    image: pdouble16/autopilotpattern-consul:1.2.0-r1
    environment:
      CONSUL: consul
      ADVERTISE_CIDR: 172.0.0.0/8
    dns: 127.0.0.1
    mem_limit: 64M
    cpu_quota: 6250
    #cpus: '0.0625'
    ports:
      - 8500

  prometheus:
    image: ${IMAGE_NAME:-pdouble16/autopilotpattern-prometheus:latest}
    environment:
      CONSUL: consul
      CONSUL_AGENT: 1
      SERVER_JVMFLAGS: -Xmx128m
      ADVERTISE_CIDR: 172.0.0.0/8
    depends_on:
      - consul
    mem_limit: 256M
    cpu_quota: 6250
    #cpus: '0.0625'
